homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Minsk
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


history_graph:
  gr1:
    name: Living room temperature
    entities:
      - sensor.sensor1_temperature
    hours_to_show: 24
    refresh: 600
  gr2:
    name: Outdoor temperature
    entities:
      - sensor.owm_temperature
    hours_to_show: 24
    refresh: 600

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'ru'

# Cloud
cloud:

group: !include groups.yaml
script: !include scripts.yaml


##  Input Slider
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches

zone: !include zones.yaml
media_player: !include media_player.yaml

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: ffmpeg
    name: Webcam
    input: /dev/video0

## Manual automations
automation old: !include_dir_merge_list automations
# UI automations
automation: !include automations.yaml


device_tracker:
  - platform: nmap_tracker
    hosts: !secret home_network
    interval_seconds: 60
    home_interval: 10

# Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id1

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

# Example configuration.yaml entry for the notifier
notify:
  - name: Telegram
    api_key: !secret telegram_api_key
    platform: telegram
    chat_id: !secret telegram_chat_id1

mqtt:
  discovery: true
  broker: 127.0.0.1
  discovery_prefix: homeassistant

# RGB:
light:
  - platform: mqtt
    schema: json
    name: mqtt_json_light_2
    state_topic: "home/ESP_LED"
    command_topic: "home/ESP_LED/set"
    brightness: true
    rgb: true
    effect: true
    effect_list: [colorfade_slow, colorfade_fast, flash]
    optimistic: false
    qos: 0


  - platform: mqtt
    schema: json  
    name: "NeoPixel LEDs"
    state_topic: "home/McLighting01_ha/state/out"
    command_topic: "home/McLighting01_ha/state/in"
    # on_command_type: 'first'
    effect: true
    effect_list:
      - "Static"
      - "Blink"
      - "Breath"
      - "Color Wipe"
      - "Color Wipe Inverse"
      - "Color Wipe Reverse"
      - "Color Wipe Reverse Inverse"
      - "Color Wipe Random"
      - "Random Color"
      - "Single Dynamic"
      - "Multi Dynamic"
      - "Rainbow"
      - "Rainbow Cycle"
      - "Scan"
      - "Dual Scan"
      - "Fade"
      - "Theater Chase"
      - "Theater Chase Rainbow"
      - "Running Lights"
      - "Twinkle"
      - "Twinkle Random"
      - "Twinkle Fade"
      - "Twinkle Fade Random"
      - "Sparkle"
      - "Flash Sparkle"
      - "Hyper Sparkle"
      - "Strobe"
      - "Strobe Rainbow"
      - "Multi Strobe"
      - "Blink Rainbow"
      - "Chase White"
      - "Chase Color"
      - "Chase Random"
      - "Chase Rainbow"
      - "Chase Flash"
      - "Chase Flash Random"
      - "Chase Rainbow White"
      - "Chase Blackout"
      - "Chase Blackout Rainbow"
      - "Color Sweep Random"
      - "Running Color"
      - "Running Red Blue"
      - "Running Random"
      - "Larson Scanner"
      - "Comet"
      - "Fireworks"
      - "Fireworks Random"
      - "Merry Christmas"
      - "Fire Flicker"
      - "Fire Flicker (soft)"
      - "Fire Flicker (intense)"
      - "Circus Combustus"
      - "Halloween"
      - "Bicolor Chase"
      - "Tricolor Chase"
      - "ICU"
    brightness: true
    color_temp: true
    rgb: true
    optimistic: false
    qos: 0
    retain: true
