############################################################
#                                                          #
#                     Group Tabs                           #
#                                                          #
############################################################
default_view:
  view: yes
  icon: mdi:home
  entities:
    - sensor.openweathermap_temperature
    - sensor.sensor1_temperature
    - sensor.sensor1_humidity
    - light.mqtt_json_light_2
    - light.neopixel_leds
    - input_number.neopixel_animation_speed
    - camera.webcam
    - group.AlarmClock
    - group.Weather
    - group.HistoryGraph
    - updater.updater



#Определяем какие элементы входят в состав группы
alarmclock:
  name: Будильник.
  entities:
    - sensor.alarm_time
    - input_number.alarmhour
    - input_number.alarmminutes
    - input_boolean.alarmweekday


#Вкладка (tab) описываем состав вкладки.
AlarmClock:
  name: Будильник
  view: yes
  icon: mdi:alarm
  entities:
    - group.alarmclock

#Вкладка (tab) описываем состав вкладки.
Weather:
  name: Погода1
  view: yes
  icon: mdi:weather-cloudy
  entities:
    - group.sun
    - group.weatherCondition
    - sensor.moon
    # - sensor.owm_cloud_coverage
    # - sensor.owm_condition
    # - sensor.owm_humidity
    # - sensor.owm_rain
    # - sensor.owm_snow
    # - sensor.owm_temperature
    # - sensor.owm_wind_speed
    # - sun.sun
HistoryGraph:
  name: История
  view: no
  icon: mdi:weather-cloudy
  entities:
    - history_graph.living_room_temperature
    - history_graph.outdoor_temperature

System:
  name: Система
  view: yes
  icon: mdi:wrench
  entities:
    - group.devPi
    - group.supervisord
    - script.restart_ha
    - switch.reboot

############################################################
#                                                          #
#                  Entities Groups                         #
#                                                          #
############################################################

Sun:
  entities:
    - sun.sun

WeatherCondition:
  entities:
    - weather.yweather
    - sensor.openweathermap_cloud_coverage
    - sensor.openweathermap_condition
    - sensor.openweathermap_humidity
    - sensor.openweathermap_rain
    - sensor.openweathermap_snow
    - sensor.openweathermap_temperature
    - sensor.openweathermap_wind_speed

devPi:
  name: Pi
  entities:
    - switch.pi_display
    - sensor.processor_use
    - sensor.cpu_temp
    - sensor.disk_use_percent
    - sensor.memory_free
    - sensor.memory_use_percent
    - sensor.since_last_boot
    - sensor.ha_last_restart
    - sensor.load_1m
    - sensor.load_5m
    - sensor.load_15m


supervisord:
  name: supervisord
  entities:
    - switch.ngrok_ssh
    - switch.pythonnoisedetection
