language: python
python:
  - "3.7"
before_install:
  - mv homeassistant/config/secrets_travis.yaml homeassistant/config/secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c homeassistant/config --script check_config
