language: python
python:
  - "3.8"
before_install:
  - mv homeassistant/config/secrets_travis.yaml homeassistant/config/secrets.yaml
install:
  - source .env && pip3 install homeassistant==$HA_VERSION
script:
  - hass -c homeassistant/config --script check_config
