# Notify when Paulus leaves the house in the evening
- alias: 'Leave Home notification'
  trigger:
    platform: state
    from: 'home'
    to: 'not_home'
    entity_id: device_tracker.Alex
  # condition:
  #   condition: time
  #   after: '20:00'
  action:
    service: notify.telegram
    data:
      message: 'Alex left the house'
