- alias: 'Arrive Home notification'
  trigger:
    platform: state
    from: 'not_home'
    to: 'home'
    entity_id: device_tracker.Alex
  condition:
    # - condition: time
    #   after: '17:00'
    - condition: state
      entity_id: input_boolean.trigger_first_alex_arrive
      state: 'on'      
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.trigger_first_alex_arrive
    - service: tts.google_say
      data:
        message: 'Привет Александр. Добро пожаловать домой'
